# Generated by Django 4.1.5 on 2023-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
