# Generated by Django 4.1.5 on 2023-02-20 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_project_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stretchgoals',
            old_name='sg_description',
            new_name='fanbased_stretchgoal',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='stretchgoals',
            name='project',
        ),
        migrations.RemoveField(
            model_name='stretchgoals',
            name='trigger',
        ),
        migrations.AddField(
            model_name='project',
            name='favourite',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='stretchgoal_trigger',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stretchgoals',
            name='pledge',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, related_name='stretch_goals', to='projects.pledge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stretchgoals',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stretch_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
