# Generated by Django 4.1.5 on 2023-01-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_pledge_is_active_alter_project_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
    ]
